language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
cache: ccache
script:
- cd MyUtility
- dotnet restore
- dotnet build -c Debug
- dotnet build -c Release
- dotnet test ./src/MyUtility.Test
- dotnet pack -c Debug --include-symbols  -o $PWD
- dotnet pack -c Release -o $PWD
- dotnet nuget push ./*.nupkg -k $mygetKey -s https://www.myget.org/F/uliian/api/v2/package
- dotnet nuget push ./*.symbols.nupkg -k $mygetKey -s https://www.myget.org/F/uliian/symbols/api/v2/package