language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
script:
- cd MyUtility
- dotnet restore
- dotnet build
- dotnet pack
- dotnet nuget push *.nupkg $mygetKey -s https://www.myget.org/feed/Packages/uliian